name: Hockeybuggy.com
description: Musings of Douglas James Anderson
header_img: "static/img/wind-river-header.jpg"

paginate: 10

sass:
  sass_dir: "static/_sass"

exclude: ["script", "node_modules"]  # TODO minify and cat assets
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
