name: Hockeybuggy.com
description: Musings of Douglas James Anderson
markdown: kramdown
highlighter: pygments
paginate: 10
exclude: ["script"]
sass:
  sass_dir: "static/_sass"

gems:
  - jekyll-feed
  - jekyll-paginate
