name: tests and linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.11.0
      uses: actions/setup-node@v1
      with:
        node-version: 13.11.0
    - name: Install
      run: |
        yarn install
    - name: Build
      env:
        CI: true
      run: |
        yarn run build
    - name: Check Types
      run: |
        yarn run typecheck
    - name: Linting
      run: |
        yarn run lint
    - name: Check Formatting
      run: |
        yarn run check-format
